import {MD3LightTheme, MD3DarkTheme} from 'react-native-paper';
export const lightTheme = {
  ...MD3LightTheme,
  version: 3,
  isDark: false,
  colors: {
    primary: '#494bd6',
    onPrimary: '#ffffff',
    primaryContainer: '#e1e0ff',
    onPrimaryContainer: '#07006c',
    secondary: '#5d5c72',
    onSecondary: '#ffffff',
    secondaryContainer: '#e2e0f9',
    onSecondaryContainer: '#191a2c',
    tertiary: '#006c4c',
    onTertiary: '#ffffff',
    tertiaryContainer: '#89f8c6',
    onTertiaryContainer: '#002114',
    background: '#fffbff',
    onBackground: '#1c1b1f',
    surface: '#fffbff',
    onSurface: '#1c1b1f',
    surfaceVariant: '#e4e1ec',
    onSurfaceVariant: '#46464f',
    outline: '#777680',
    error: '#ba1a1a',
    onError: '#ffffff',
    errorContainer: '#ffdad6',
    onErrorContainer: '#410002',
    elevation: MD3LightTheme.elevation,
  },
};

export const darkTheme = {
  ...MD3DarkTheme,
  version: 3,
  isDark: true,
  colors: {
    mode: 'adaptive',
    primary: '#c0c1ff',
    onPrimary: '#1000a9',
    primaryContainer: '#2f2ebe',
    onPrimaryContainer: '#e1e0ff',
    secondary: '#c6c4dd',
    onSecondary: '#2e2f42',
    secondaryContainer: '#454559',
    onSecondaryContainer: '#e2e0f9',
    tertiary: '#6cdbac',
    onTertiary: '#003826',
    tertiaryContainer: '#005138',
    onTertiaryContainer: '#89f8c6',
    background: '#1c1b1f',
    onBackground: '#e5e1e6',
    surface: '#1c1b1f',
    onSurface: '#e5e1e6',
    surfaceVariant: '#46464f',
    onSurfaceVariant: '#46464f',
    outline: '#918f9a',
    error: '#ffb4ab',
    onError: '#690005',
    errorContainer: '#93000a',
    onErrorContainer: '#ffdad6',
    elevation: MD3DarkTheme.elevation,
  },
};
